name: Sync labels

on:
  workflow_dispatch:
  push:
    paths:
      - .github/labels.yml

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crazy-max/ghaction-github-labeler@v5
        with:
          yaml_file: .github/labels.yml
          skip_delete: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}